# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user1@notfound.local",
  "name": "Keks",
  "password": "123456"
}

###

# check auth
GET http://localhost:3000/api/auth/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQG5vdGZvdW5kLmxvY2FsIiwic3ViIjoiM2FlNGE5ZjUtZmFlOC00ODdhLTkyMDAtM2NiZmI5NjRjNGViIiwiaWF0IjoxNzUyMzYzODM1LCJleHAiOjE3NTIzNjc0MzV9.M9ZYhdWeFlq2nt4aeTdXxQ8eq1bmtGo4dBquohc0Q3Y

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user3@notfound.local",
  "password": "123456"
}

###

